"""Tạo bảng sinh viên

Revision ID: 01e090a32755
Revises: 93db08ab0f3e
Create Date: 2021-12-12 14:39:12.527401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e090a32755'
down_revision = '93db08ab0f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sinhvien',
    sa.Column('masv', sa.String(length=50), nullable=False),
    sa.Column('hoten', sa.String(length=255), nullable=True),
    sa.Column('diachi', sa.String(length=255), nullable=True),
    sa.Column('nganh', sa.String(length=255), nullable=True),
    sa.Column('khoa', sa.String(length=255), nullable=True),
    sa.Column('sodt', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('masv')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sinhvien')
    # ### end Alembic commands ###
