"""Them lai bang loaisach

Revision ID: 0930bcfa08d1
Revises: 7be41da45296
Create Date: 2021-12-07 17:17:19.137485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0930bcfa08d1'
down_revision = '7be41da45296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loaisach',
    sa.Column('maloai', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenloai', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('maloai')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loaisach')
    # ### end Alembic commands ###
