"""xoa bang tai khoan

Revision ID: 22041ab3b155
Revises: e67c3f4b799b
Create Date: 2021-12-14 18:52:13.317954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22041ab3b155'
down_revision = 'e67c3f4b799b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taikhoan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taikhoan',
    sa.Column('tendangnhap', sa.VARCHAR(length=50), nullable=False),
    sa.Column('matkhau', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('tendangnhap')
    )
    # ### end Alembic commands ###
