"""xoa bang loaisach

Revision ID: 7be41da45296
Revises: 8a2a34c5d6bc
Create Date: 2021-12-07 17:16:41.081182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be41da45296'
down_revision = '8a2a34c5d6bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loaisach')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loaisach',
    sa.Column('maloai', sa.INTEGER(), nullable=False),
    sa.Column('tenloai', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('maloai')
    )
    # ### end Alembic commands ###
