"""them lai bang tai khoan

Revision ID: 7ce90a4b95c1
Revises: 22041ab3b155
Create Date: 2021-12-14 18:53:57.540850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce90a4b95c1'
down_revision = '22041ab3b155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taikhoan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tendangnhap', sa.String(length=50), nullable=True),
    sa.Column('matkhau', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tendangnhap')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taikhoan')
    # ### end Alembic commands ###
