"""tao bang tai khoan

Revision ID: 8a2a34c5d6bc
Revises: 
Create Date: 2021-12-07 17:09:02.412576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2a34c5d6bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loaisach',
    sa.Column('maloai', sa.Integer(), nullable=False),
    sa.Column('tenloai', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('maloai')
    )
    op.create_table('taikhoan',
    sa.Column('tendangnhap', sa.String(length=50), nullable=False),
    sa.Column('matkhau', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('tendangnhap')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taikhoan')
    op.drop_table('loaisach')
    # ### end Alembic commands ###
