"""tao bang sach

Revision ID: 93db08ab0f3e
Revises: 0930bcfa08d1
Create Date: 2021-12-12 14:32:38.540147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93db08ab0f3e'
down_revision = '0930bcfa08d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sach',
    sa.Column('masach', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tensach', sa.String(length=255), nullable=True),
    sa.Column('maloai', sa.Integer(), nullable=True),
    sa.Column('tenloai', sa.String(length=255), nullable=True),
    sa.Column('tacgia', sa.String(length=255), nullable=True),
    sa.Column('nhaxuatban', sa.String(length=255), nullable=True),
    sa.Column('soluong', sa.Integer(), nullable=True),
    sa.Column('gia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['maloai'], ['loaisach.maloai'], ),
    sa.PrimaryKeyConstraint('masach')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sach')
    # ### end Alembic commands ###
