"""update table sach

Revision ID: 98be918b3949
Revises: 7ce90a4b95c1
Create Date: 2021-12-20 00:20:31.449389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98be918b3949'
down_revision = '7ce90a4b95c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sach', sa.Column('tenloaisach', sa.String(length=255), nullable=True))
    op.drop_column('sach', 'tenloai')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sach', sa.Column('tenloai', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('sach', 'tenloaisach')
    # ### end Alembic commands ###
