"""tạo bảng đơn mượn

Revision ID: e67c3f4b799b
Revises: 01e090a32755
Create Date: 2021-12-12 15:25:03.955895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67c3f4b799b'
down_revision = '01e090a32755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donmuon',
    sa.Column('madonmuon', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('masv', sa.String(length=50), nullable=True),
    sa.Column('hoten', sa.String(length=255), nullable=True),
    sa.Column('masach', sa.Integer(), nullable=True),
    sa.Column('tensach', sa.String(length=255), nullable=True),
    sa.Column('ngaymuon', sa.DateTime(), nullable=True),
    sa.Column('hantra', sa.DateTime(), nullable=True),
    sa.Column('trangthai', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['masach'], ['sach.masach'], ),
    sa.ForeignKeyConstraint(['masv'], ['sinhvien.masv'], ),
    sa.PrimaryKeyConstraint('madonmuon')
    )
    op.create_index(op.f('ix_donmuon_hantra'), 'donmuon', ['hantra'], unique=False)
    op.create_index(op.f('ix_donmuon_ngaymuon'), 'donmuon', ['ngaymuon'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donmuon_ngaymuon'), table_name='donmuon')
    op.drop_index(op.f('ix_donmuon_hantra'), table_name='donmuon')
    op.drop_table('donmuon')
    # ### end Alembic commands ###
